### ISSUE TITLE
tool rename?

### ISSUE THREAD

**Issue by matthandlersux** [Originate/check-protocols#104]
@soenkehahn you mentioned you were considering renaming this library. i figure it's something we can discuss/post suggestions for here.

**Comment by matthandlersux** [comment]
how about: "scriptkeeper"?

![getinsertpic.com](https://media0.giphy.com/media/grMbJNpgYrAQM/200.gif)

**Comment by soenkehahn** [comment]
Someone once suggested 'Mockey Mouse'.

**Comment by soenkehahn** [comment]
`script-adlib`?

**Comment by soenkehahn** [comment]
`scrypt`? `scrypto`?

**Comment by soenkehahn** [comment]
`script-kit`?

**Comment by soenkehahn** [comment]
`script-under-test`?

**Comment by matthandlersux** [comment]
`script-kitty`

**Comment by data-pup** [comment]
`tesht`?

**Comment by matthandlersux** [comment]
@xasopheno ?

**Comment by soenkehahn** [comment]
If no one objects, we'll go with `scriptkeeper`. Closing in favor of #171.
