### ISSUE TITLE
allow to specify arguments with spaces that get passed to the tested script

### ISSUE THREAD

**Issue by astampoulis** [Originate/check-protocols#66]
`check-protocols` allows to pass in arguments to the tested script:

``` bash
#!/usr/bin/env bash
mv $1 $2
```

``` yaml
arguments: foo bar
protocol:
  - mv foo bar
```

The string passed in through the `arguments` field is split into arguments by spaces. So currently there is no way to pass in arguments that contain spaces. (The arguments parsing should follow the same rules as the parsing for expected arguments for the individual steps, as in #67.)

**Comment by matthandlersux** [comment]
i think this is the same as #67

**Comment by soenkehahn** [comment]
@matthandlersux: No, but this probably should be explained better. I changed this issue description, hope it's clearer now.
