### ISSUE TITLE
indicate clearly when there's a yaml parse error

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#77]
Currently an error gets reported, but it's not always clear that the error comes from trying to parse the yaml file. Example:

`error: block sequence entries are not allowed in this context`

From this yaml file:
``` yaml
protocol: - foo
```

It should say something like:

`error parsing foo.protocols.yaml: block sequence entries are not allowed in this context`

@matthandlersux: I think you mentioned this somewhere, but I can't find it.

**Comment by matthandlersux** [comment]
i think i mentioned this IRL
