### ISSUE TITLE
allow to create protocols by running the tested scripts

### ISSUE THREAD

**Issue by soenkehahn** [Originate/check-protocols#85]
It should be possible to create a protocols file by running `check-protocols` against a script file somehow. It would capture the issued commands and put them into the protocol.

**Comment by soenkehahn** [comment]
cc: @xasopheno

**Comment by matthandlersux** [comment]
should this capture every syscall? based on the debug output i've seen, there are probably many syscalls that one would want to ignore.

**Comment by soenkehahn** [comment]
No, not every syscall. This should support all the features that are supported by checking protocols. So that includes some syscalls, but also other things, e.g. the exitcode of the tested script.
