### ISSUE TITLE
add short description to repo

### ISSUE THREAD

**Issue by matthandlersux** [Originate/check-protocols#94]
would be nice to have a one-liner so that this is not empty:

![screen shot 2019-02-28 at 11 58 34 am](https://user-images.githubusercontent.com/72524/53583777-3db1dd80-3b50-11e9-821a-901d2973e085.png)

**Comment by soenkehahn** [comment]
@matthandlersux: What do you think about the current description?

**Comment by matthandlersux** [comment]
hah, i guess we were both thinking about this at the same time. come join me over in #99
