### ISSUE TITLE
Add more script examples to documentation

### ISSUE THREAD

**Issue by data-pup** [Originate/check-protocols#98]
Once more of this project stabilises, we might want to set up documentation with [mdbook](https://github.com/rust-lang-nursery/mdBook). This would let us publish more detailed docs to GitHub Pages :)

One example would be talking about protocols in more depth. The example in the `README` covers a simple shell script, but the largest benefit of this idea comes when scripts in other languages shell out with dynamically generated commands. We could cover a simple example like that, and so on.

**Comment by soenkehahn** [comment]
Should we change the title of this issue to something like 'Add more elaborate script examples to documentation'? So that we focus on a problem to solve and not on a proposed solution? (I think ideally whether to use mdbook or not should be mostly up to the person picking up this ticket.)

**Comment by data-pup** [comment]
Good point. I'll change the title of this, and we can take care of that point first. `mdbook` is nice, but probably not needed until the `README` becomes too large. :+1:
